[Typeregistry-EOSC]
url="http://typeregistry.lab.pidconsortium.net/"
suffix="objects?query=*"
style="eosc"
types=["BasicInfoType","InfoType","Profile"]
units=["MeasurementUnit"]
taxonomy=["TaxonomyNode"]
general=["ExtendedMimeType"]
